INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (1, 500, 'Honda Civic', 1, 'civic.jpg', 'Honda Civic', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (2, 700, 'Honda CRV', 1, 'crv.jpg', 'Honda CRV', 2, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (3, 500, 'Honda HRV', 1, 'hrv.jpg', 'Honda HRV', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (4, 300, 'Honda Fit', 1, 'fit.jpg', 'Honda Fit', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (5, 300, 'Citroen C3', 1, 'c3.jpg', 'Citroen C3', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (6, 450, 'Citroen C4', 1, 'c4.jpg', 'Citroen C4', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (7, 300, 'Citroen C1', 1, 'c1.jpg', 'Citroen C1', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (8, 550, 'Citroen C3 Aircross', 1, 'c3-aircross.jpg', 'Citroen C3 Aircross', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (9, 500, 'Ford Focus', 1, 'focus.jpg', 'Ford Focus', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (10, 400, 'Ford Fiesta', 1, 'fiesta.jpg', 'Ford Fiesta', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (11, 300, 'Ford Ka', 1, 'ka.jpg', 'Ford Ka', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (12, 600, 'Ford EcoSport', 1, 'ecosport.jpg', 'Ford EcoSport', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (13, 800, 'Ford Kuga', 1, 'kuga.jpg', 'Ford Kuga', 2, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (14, 1200, 'Ford Mustang', 1, 'mustang.jpg', 'Ford Mustang', 3, 3)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (15, 1000, 'Ford Fusion', 1, 'fusion.jpg', 'Ford Fusion', 3, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (16, 800, 'Chevrolet Cruze', 1, 'cruze.jpg', 'Chevrolet Cruze', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (17, 600, 'Chevrolet Astra', 1, 'astra.jpg', 'Chevrolet Astra', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (18, 400, 'Chevrolet Agile', 1, 'agile.jpg', 'Chevrolet Agile', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (19, 250, 'Chevrolet Corsa', 1, 'corsa.jpg', 'Chevrolet Corsa', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (20, 900, 'Chevrolet Captiva', 1, 'captiva.jpg', 'Chevrolet Captiva', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (21, 500, 'Chevrolet Onix', 1, 'onix.jpg', 'Chevrolet Onix', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (22, 1400, 'Chevrolet Camaro', 1, 'camaro.jpg', 'Chevrolet Camaro', 3, 3)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (23, 2500, 'Chevrolet Corvette', 1, 'corvette.jpg', 'Chevrolet Corvette', 3, 3)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (24, 300, 'Volkswagen Gol', 1, 'gol.jpg', 'Volkswagen Gol', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (25, 750, 'Volkswagen Golf', 1, 'golf.jpg', 'Volkswagen Golf', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (26, 800, 'Volkswagen Passat', 1, 'passat.jpg', 'Volkswagen Passat', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (27, 600, 'Volkswagen Vento', 1, 'vento.jpg', 'Volkswagen Vento', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (28, 1000, 'Volkswagen Sirocco', 1, 'sirocco.jpg', 'Volkswagen Sirocco', 3, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (29, 500, 'Volkswagen Up!', 1, 'up.jpg', 'Volkswagen Up!', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (30, 500, 'Volkswagen Voyage', 1, 'voyage.jpg', 'Volkswagen Voyage', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (31, 550, 'Volkswagen Polo', 1, 'polo.jpg', 'Volkswagen Polo', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (32, 350, 'Volkswagen Fox', 1, 'fox.jpg', 'Volkswagen Fox', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (33, 700, 'Volkswagen The Beetle', 1, 'beetle.jpg', 'Volkswagen The Beetle', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (34, 600, 'Volkswagen Tiguan', 1, 'tiguan.jpg', 'Volkswagen Tiguan', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (35, 650, 'Volkswagen Touareg', 1, 'touareg.jpg', 'Volkswagen Touareg', 2, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (36, 400, 'Renault Kangoo', 1, 'kangoo.jpg', 'Renault Kangoo', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (37, 400, 'Renault Megane', 1, 'megane.jpg', 'Renault Megane', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (38, 600, 'Renault Fluence', 1, 'fluence.jpg', 'Renault Fluence', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (39, 700, 'Renault Duster', 1, 'duster.jpg', 'Renault Duster', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (40, 800, 'Renault Koleos', 1, 'koleos.jpg', 'Renault Koleos', 2, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (41, 400, 'Renault Stepway', 1, 'stepway.jpg', 'Renault Stepway', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (42, 300, 'Renault Logan', 1, 'logan.jpg', 'Renault Logan', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (43, 500, 'Honda Civic', 2, 'civic.jpg', 'Honda Civic', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (44, 500, 'Honda HRV', 2, 'hrv.jpg', 'Honda HRV', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (45, 300, 'Honda Fit', 2, 'fit.jpg', 'Honda Fit', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (46, 450, 'Citroen C4', 2, 'c4.jpg', 'Citroen C4', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (47, 550, 'Citroen C3 Aircross', 2, 'c3-aircross.jpg', 'Citroen C3 Aircross', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (48, 400, 'Ford Fiesta', 2, 'fiesta.jpg', 'Ford Fiesta', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (49, 600, 'Ford EcoSport', 2, 'ecosport.jpg', 'Ford EcoSport', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (50, 1200, 'Ford Mustang', 2, 'mustang.jpg', 'Ford Mustang', 3, 3)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (51, 800, 'Chevrolet Cruze', 2, 'cruze.jpg', 'Chevrolet Cruze', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (52, 400, 'Chevrolet Agile', 2, 'agile.jpg', 'Chevrolet Agile', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (53, 900, 'Chevrolet Captiva', 2, 'captiva.jpg', 'Chevrolet Captiva', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (54, 1400, 'Chevrolet Camaro', 2, 'camaro.jpg', 'Chevrolet Camaro', 3, 3)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (55, 300, 'Volkswagen Gol', 2, 'gol.jpg', 'Volkswagen Gol', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (56, 800, 'Volkswagen Passat', 2, 'passat.jpg', 'Volkswagen Passat', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (57, 1000, 'Volkswagen Sirocco', 2, 'sirocco.jpg', 'Volkswagen Sirocco', 3, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (58, 500, 'Volkswagen Voyage', 2, 'voyage.jpg', 'Volkswagen Voyage', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (59, 350, 'Volkswagen Fox', 2, 'fox.jpg', 'Volkswagen Fox', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (60, 600, 'Volkswagen Tiguan', 2, 'tiguan.jpg', 'Volkswagen Tiguan', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (61, 400, 'Renault Kangoo', 2, 'kangoo.jpg', 'Renault Kangoo', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (62, 600, 'Renault Fluence', 2, 'fluence.jpg', 'Renault Fluence', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (63, 800, 'Renault Koleos', 2, 'koleos.jpg', 'Renault Koleos', 2, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (64, 300, 'Renault Logan', 2, 'logan.jpg', 'Renault Logan', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (65, 500, 'Honda HRV', 3, 'hrv.jpg', 'Honda HRV', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (66, 450, 'Citroen C4', 3, 'c4.jpg', 'Citroen C4', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (67, 500, 'Ford Focus', 3, 'focus.jpg', 'Ford Focus', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (68, 600, 'Ford EcoSport', 3, 'ecosport.jpg', 'Ford EcoSport', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (69, 1000, 'Ford Fusion', 3, 'fusion.jpg', 'Ford Fusion', 3, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (70, 400, 'Chevrolet Agile', 3, 'agile.jpg', 'Chevrolet Agile', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (71, 500, 'Chevrolet Onix', 3, 'onix.jpg', 'Chevrolet Onix', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (72, 300, 'Volkswagen Gol', 3, 'gol.jpg', 'Volkswagen Gol', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (73, 600, 'Volkswagen Vento', 3, 'vento.jpg', 'Volkswagen Vento', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (74, 500, 'Volkswagen Voyage', 3, 'voyage.jpg', 'Volkswagen Voyage', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (75, 700, 'Volkswagen The Beetle', 3, 'beetle.jpg', 'Volkswagen The Beetle', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (76, 400, 'Renault Kangoo', 3, 'kangoo.jpg', 'Renault Kangoo', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (77, 700, 'Renault Duster', 3, 'duster.jpg', 'Renault Duster', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (78, 300, 'Renault Logan', 3, 'logan.jpg', 'Renault Logan', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (79, 700, 'Honda CRV', 4, 'crv.jpg', 'Honda CRV', 2, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (80, 300, 'Honda Fit', 4, 'fit.jpg', 'Honda Fit', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (81, 450, 'Citroen C4', 4, 'c4.jpg', 'Citroen C4', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (82, 550, 'Citroen C3 Aircross', 4, 'c3-aircross.jpg', 'Citroen C3 Aircross', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (83, 400, 'Ford Fiesta', 4, 'fiesta.jpg', 'Ford Fiesta', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (84, 600, 'Ford EcoSport', 4, 'ecosport.jpg', 'Ford EcoSport', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (85, 1200, 'Ford Mustang', 4, 'mustang.jpg', 'Ford Mustang', 3, 3)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (86, 800, 'Chevrolet Cruze', 4, 'cruze.jpg', 'Chevrolet Cruze', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (87, 400, 'Chevrolet Agile', 4, 'agile.jpg', 'Chevrolet Agile', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (88, 900, 'Chevrolet Captiva', 4, 'captiva.jpg', 'Chevrolet Captiva', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (89, 1400, 'Chevrolet Camaro', 4, 'camaro.jpg', 'Chevrolet Camaro', 3, 3)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (90, 300, 'Volkswagen Gol', 4, 'gol.jpg', 'Volkswagen Gol', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (91, 800, 'Volkswagen Passat', 4, 'passat.jpg', 'Volkswagen Passat', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (92, 1000, 'Volkswagen Sirocco', 4, 'sirocco.jpg', 'Volkswagen Sirocco', 3, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (93, 500, 'Volkswagen Voyage', 4, 'voyage.jpg', 'Volkswagen Voyage', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (94, 350, 'Volkswagen Fox', 4, 'fox.jpg', 'Volkswagen Fox', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (95, 600, 'Volkswagen Tiguan', 4, 'tiguan.jpg', 'Volkswagen Tiguan', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (96, 400, 'Renault Kangoo', 4, 'kangoo.jpg', 'Renault Kangoo', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (97, 600, 'Renault Fluence', 4, 'fluence.jpg', 'Renault Fluence', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (98, 800, 'Renault Koleos', 4, 'koleos.jpg', 'Renault Koleos', 2, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (99, 300, 'Renault Logan', 4, 'logan.jpg', 'Renault Logan', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (100, 300, 'Citroen C3', 5, 'c3.jpg', 'Citroen C3', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (101, 450, 'Citroen C4', 5, 'c4.jpg', 'Citroen C4', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (102, 500, 'Ford Focus', 5, 'focus.jpg', 'Ford Focus', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (103, 400, 'Ford Fiesta', 5, 'fiesta.jpg', 'Ford Fiesta', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (104, 300, 'Ford Ka', 5, 'ka.jpg', 'Ford Ka', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (105, 600, 'Ford EcoSport', 5, 'ecosport.jpg', 'Ford EcoSport', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (106, 800, 'Ford Kuga', 5, 'kuga.jpg', 'Ford Kuga', 2, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (107, 1200, 'Ford Mustang', 5, 'mustang.jpg', 'Ford Mustang', 3, 3)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (108, 1000, 'Ford Fusion', 5, 'fusion.jpg', 'Ford Fusion', 3, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (109, 800, 'Chevrolet Cruze', 5, 'cruze.jpg', 'Chevrolet Cruze', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (110, 250, 'Chevrolet Corsa', 5, 'corsa.jpg', 'Chevrolet Corsa', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (111, 2500, 'Chevrolet Corvette', 5, 'corvette.jpg', 'Chevrolet Corvette', 3, 3)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (112, 1000, 'Volkswagen Sirocco', 5, 'sirocco.jpg', 'Volkswagen Sirocco', 3, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (113, 500, 'Volkswagen Up!', 5, 'up.jpg', 'Volkswagen Up!', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (114, 350, 'Volkswagen Fox', 5, 'fox.jpg', 'Volkswagen Fox', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (115, 700, 'Volkswagen The Beetle', 5, 'beetle.jpg', 'Volkswagen The Beetle', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (116, 400, 'Renault Kangoo', 5, 'kangoo.jpg', 'Renault Kangoo', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (117, 700, 'Renault Duster', 5, 'duster.jpg', 'Renault Duster', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (118, 300, 'Renault Logan', 5, 'logan.jpg', 'Renault Logan', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (119, 700, 'Honda CRV', 6, 'crv.jpg', 'Honda CRV', 2, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (120, 500, 'Honda HRV', 6, 'hrv.jpg', 'Honda HRV', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (121, 300, 'Honda Fit', 6, 'fit.jpg', 'Honda Fit', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (122, 300, 'Citroen C3', 6, 'c3.jpg', 'Citroen C3', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (123, 450, 'Citroen C4', 6, 'c4.jpg', 'Citroen C4', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (124, 500, 'Ford Focus', 6, 'focus.jpg', 'Ford Focus', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (125, 400, 'Ford Fiesta', 6, 'fiesta.jpg', 'Ford Fiesta', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (126, 300, 'Ford Ka', 6, 'ka.jpg', 'Ford Ka', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (127, 600, 'Ford EcoSport', 6, 'ecosport.jpg', 'Ford EcoSport', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (128, 1200, 'Ford Mustang', 6, 'mustang.jpg', 'Ford Mustang', 3, 3)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (129, 1000, 'Ford Fusion', 6, 'fusion.jpg', 'Ford Fusion', 3, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (130, 800, 'Chevrolet Cruze', 6, 'cruze.jpg', 'Chevrolet Cruze', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (131, 600, 'Chevrolet Astra', 6, 'astra.jpg', 'Chevrolet Astra', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (132, 400, 'Chevrolet Agile', 6, 'agile.jpg', 'Chevrolet Agile', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (133, 500, 'Chevrolet Onix', 6, 'onix.jpg', 'Chevrolet Onix', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (134, 1400, 'Chevrolet Camaro', 6, 'camaro.jpg', 'Chevrolet Camaro', 3, 3)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (135, 2500, 'Chevrolet Corvette', 6, 'corvette.jpg', 'Chevrolet Corvette', 3, 3)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (136, 750, 'Volkswagen Golf', 6, 'golf.jpg', 'Volkswagen Golf', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (137, 800, 'Volkswagen Passat', 6, 'passat.jpg', 'Volkswagen Passat', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (138, 600, 'Volkswagen Vento', 6, 'vento.jpg', 'Volkswagen Vento', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (139, 500, 'Volkswagen Up!', 6, 'up.jpg', 'Volkswagen Up!', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (140, 500, 'Volkswagen Voyage', 6, 'voyage.jpg', 'Volkswagen Voyage', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (141, 350, 'Volkswagen Fox', 6, 'fox.jpg', 'Volkswagen Fox', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (142, 700, 'Volkswagen The Beetle', 6, 'beetle.jpg', 'Volkswagen The Beetle', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (143, 650, 'Volkswagen Touareg', 6, 'touareg.jpg', 'Volkswagen Touareg', 2, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (144, 600, 'Renault Fluence', 6, 'fluence.jpg', 'Renault Fluence', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (145, 800, 'Renault Koleos', 6, 'koleos.jpg', 'Renault Koleos', 2, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (146, 300, 'Citroen C3', 7, 'c3.jpg', 'Citroen C3', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (147, 450, 'Citroen C4', 7, 'c4.jpg', 'Citroen C4', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (148, 300, 'Citroen C1', 7, 'c1.jpg', 'Citroen C1', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (149, 550, 'Citroen C3 Aircross', 7, 'c3-aircross.jpg', 'Citroen C3 Aircross', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (150, 500, 'Ford Focus', 7, 'focus.jpg', 'Ford Focus', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (151, 400, 'Ford Fiesta', 7, 'fiesta.jpg', 'Ford Fiesta', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (152, 300, 'Ford Ka', 7, 'ka.jpg', 'Ford Ka', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (153, 600, 'Ford EcoSport', 7, 'ecosport.jpg', 'Ford EcoSport', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (154, 800, 'Ford Kuga', 7, 'kuga.jpg', 'Ford Kuga', 2, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (155, 1200, 'Ford Mustang', 7, 'mustang.jpg', 'Ford Mustang', 3, 3)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (156, 1000, 'Ford Fusion', 7, 'fusion.jpg', 'Ford Fusion', 3, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (157, 800, 'Chevrolet Cruze', 7, 'cruze.jpg', 'Chevrolet Cruze', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (158, 600, 'Chevrolet Astra', 7, 'astra.jpg', 'Chevrolet Astra', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (159, 400, 'Chevrolet Agile', 7, 'agile.jpg', 'Chevrolet Agile', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (160, 250, 'Chevrolet Corsa', 7, 'corsa.jpg', 'Chevrolet Corsa', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (161, 900, 'Chevrolet Captiva', 7, 'captiva.jpg', 'Chevrolet Captiva', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (162, 500, 'Chevrolet Onix', 7, 'onix.jpg', 'Chevrolet Onix', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (163, 1400, 'Chevrolet Camaro', 7, 'camaro.jpg', 'Chevrolet Camaro', 3, 3)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (164, 2500, 'Chevrolet Corvette', 7, 'corvette.jpg', 'Chevrolet Corvette', 3, 3)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (165, 500, 'Honda Civic', 8, 'civic.jpg', 'Honda Civic', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (166, 700, 'Honda CRV', 8, 'crv.jpg', 'Honda CRV', 2, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (167, 500, 'Honda HRV', 8, 'hrv.jpg', 'Honda HRV', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (168, 300, 'Honda Fit', 8, 'fit.jpg', 'Honda Fit', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (169, 300, 'Citroen C3', 8, 'c3.jpg', 'Citroen C3', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (170, 450, 'Citroen C4', 8, 'c4.jpg', 'Citroen C4', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (171, 300, 'Citroen C1', 8, 'c1.jpg', 'Citroen C1', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (172, 550, 'Citroen C3 Aircross', 8, 'c3-aircross.jpg', 'Citroen C3 Aircross', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (173, 300, 'Volkswagen Gol', 8, 'gol.jpg', 'Volkswagen Gol', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (174, 750, 'Volkswagen Golf', 8, 'golf.jpg', 'Volkswagen Golf', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (175, 800, 'Volkswagen Passat', 8, 'passat.jpg', 'Volkswagen Passat', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (176, 600, 'Volkswagen Vento', 8, 'vento.jpg', 'Volkswagen Vento', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (177, 1000, 'Volkswagen Sirocco', 8, 'sirocco.jpg', 'Volkswagen Sirocco', 3, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (178, 500, 'Volkswagen Up!', 8, 'up.jpg', 'Volkswagen Up!', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvIdProvinciainica, Foto, Nombre, Gama, Categoria)
VALUES (179, 500, 'Volkswagen Voyage', 8, 'voyage.jpg', 'Volkswagen Voyage', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (180, 550, 'Volkswagen Polo', 8, 'polo.jpg', 'Volkswagen Polo', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (181, 350, 'Volkswagen Fox', 8, 'fox.jpg', 'Volkswagen Fox', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (182, 700, 'Volkswagen The Beetle', 8, 'beetle.jpg', 'Volkswagen The Beetle', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (183, 600, 'Volkswagen Tiguan', 8, 'tiguan.jpg', 'Volkswagen Tiguan', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (184, 650, 'Volkswagen Touareg', 8, 'touareg.jpg', 'Volkswagen Touareg', 2, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (185, 750, 'Volkswagen Golf', 9, 'golf.jpg', 'Volkswagen Golf', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (186, 800, 'Volkswagen Passat', 9, 'passat.jpg', 'Volkswagen Passat', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (187, 600, 'Volkswagen Vento', 9, 'vento.jpg', 'Volkswagen Vento', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (188, 1000, 'Volkswagen Sirocco', 9, 'sirocco.jpg', 'Volkswagen Sirocco', 3, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (189, 500, 'Volkswagen Up!', 9, 'up.jpg', 'Volkswagen Up!', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (190, 500, 'Volkswagen Voyage', 9, 'voyage.jpg', 'Volkswagen Voyage', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (191, 550, 'Volkswagen Polo', 9, 'polo.jpg', 'Volkswagen Polo', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (192, 350, 'Volkswagen Fox', 9, 'fox.jpg', 'Volkswagen Fox', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (193, 700, 'Volkswagen The Beetle', 9, 'beetle.jpg', 'Volkswagen The Beetle', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (194, 600, 'Volkswagen Tiguan', 9, 'tiguan.jpg', 'Volkswagen Tiguan', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (195, 650, 'Volkswagen Touareg', 9, 'touareg.jpg', 'Volkswagen Touareg', 2, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (196, 400, 'Renault Kangoo', 9, 'kangoo.jpg', 'Renault Kangoo', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (197, 400, 'Renault Megane', 9, 'megane.jpg', 'Renault Megane', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (198, 600, 'Renault Fluence', 9, 'fluence.jpg', 'Renault Fluence', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (199, 700, 'Renault Duster', 9, 'duster.jpg', 'Renault Duster', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (200, 800, 'Renault Koleos', 9, 'koleos.jpg', 'Renault Koleos', 2, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (201, 400, 'Renault Stepway', 9, 'stepway.jpg', 'Renault Stepway', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (202, 300, 'Renault Logan', 9, 'logan.jpg', 'Renault Logan', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (203, 500, 'Honda Civic', 10, 'civic.jpg', 'Honda Civic', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (204, 700, 'Honda CRV', 10, 'crv.jpg', 'Honda CRV', 2, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (205, 500, 'Honda HRV', 10, 'hrv.jpg', 'Honda HRV', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (206, 300, 'Honda Fit', 10, 'fit.jpg', 'Honda Fit', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (207, 500, 'Ford Focus', 10, 'focus.jpg', 'Ford Focus', 2, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (208, 400, 'Ford Fiesta', 10, 'fiesta.jpg', 'Ford Fiesta', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (209, 300, 'Ford Ka', 10, 'ka.jpg', 'Ford Ka', 1, 1)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (210, 600, 'Ford EcoSport', 10, 'ecosport.jpg', 'Ford EcoSport', 1, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (211, 800, 'Ford Kuga', 10, 'kuga.jpg', 'Ford Kuga', 2, 2)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (212, 1200, 'Ford Mustang', 10, 'mustang.jpg', 'Ford Mustang', 3, 3)
INSERT INTO Autos(IdAuto, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Gama, Categoria)
VALUES (213, 1000, 'Ford Fusion', 10, 'fusion.jpg', 'Ford Fusion', 3, 1)


INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (1, 'Buenos Aires')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (2, 'Capital Federal')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (3, 'Córdoba')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (4, 'Mendoza')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (5, 'Santa Fe')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (6, 'La Rioja')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (7, 'Misiones')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (8, 'San Juan')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (9, 'San Luis')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (10, 'Neuquen')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (11, 'Tucuman')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (12, 'Salta')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (13, 'Jujuy')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (14, 'Entre Ríos')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (15, 'Corrientes')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (16, 'Santa Cruz')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (17, 'Río Negro')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (18, 'Chaco')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (19, 'Chubut')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (20, 'Formosa')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (21, 'Santiago Del Estero')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (22, 'Tierra Del Fuego')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (23, 'La Pampa')
INSERT INTO Provincias (IdProvincia, Nombre)
VALUES (24, 'Catamarca')

INSERT INTO Pagos (IdPago, MetodoPago)
VALUES (1, 'Tarjeta De Credito')
INSERT INTO Pagos (IdPago, MetodoPago)
VALUES (2, 'Tarjeta De Credito')
INSERT INTO Pagos (IdPago, MetodoPago)
VALUES (3, 'Tarjeta De Credito')
INSERT INTO Pagos (IdPago, MetodoPago)
VALUES (4, 'Tarjeta De Credito')
INSERT INTO Pagos (IdPago, MetodoPago)
VALUES (5, 'Tarjeta De Credito')
INSERT INTO Pagos (IdPago, MetodoPago)
VALUES (6, 'Tarjeta De Credito')
INSERT INTO Pagos (IdPago, MetodoPago)
VALUES (7, 'Tarjeta De Credito')
INSERT INTO Pagos (IdPago, MetodoPago)
VALUES (8, 'Tarjeta De Credito')
INSERT INTO Pagos (IdPago, MetodoPago)
VALUES (9, 'Efectivo')
INSERT INTO Pagos (IdPago, MetodoPago)
VALUES (10, 'Efectivo') 
INSERT INTO Pagos (IdPago, MetodoPago)
VALUES (11, 'Efectivo')
INSERT INTO Pagos (IdPago, MetodoPago)
VALUES (12, 'Efectivo')
INSERT INTO Pagos (IdPago, MetodoPago)
VALUES (13, 'Efectivo')
INSERT INTO Pagos (IdPago, MetodoPago)
VALUES (14, 'Efectivo')
INSERT INTO Pagos (IdPago, MetodoPago)
VALUES (15, 'Efectivo')
INSERT INTO Pagos (IdPago, MetodoPago)
VALUES (16, 'Efectivo')
INSERT INTO Pagos (IdPago, MetodoPago)
VALUES (17, 'Efectivo')

INSERT INTO Usuarios (IdUsuario, Email, Nombre, Foto, Password)
VALUES (1, 'pbrea@gmail.com', 'Pablo Brea', 'pablo.jpg', 'aterrizar')
INSERT INTO Usuarios (IdUsuario, Email, Nombre, Foto, Password)
VALUES (2, 'lucas.giuri@gmail.com', 'Lucas Giuri', 'lucas.jpg', 'aterrizar')
INSERT INTO Usuarios (IdUsuario, Email, Nombre, Foto, Password)
VALUES (3, 'mcelestem94@gmail.com', 'Celeste Martins', 'celeste.jpg', 'aterrizar')
INSERT INTO Usuarios (IdUsuario, Email, Nombre, Foto, Password)
VALUES (4, 'Kevin@ort.edu.ar', 'Kevin Stambulsky', 'kevin.jpg', 'aterrizar')


INSERT INTO Hoteles (IdHotel, PrecioPorDia, Descripcion, IdProvincia, Foto, Nombre, Categoria, Cantidad)
VALUES (4, 9000, 'All inclusive y spa', 1, 'tandilhotel.jpg', 'Tandil hotel spa', 5, 6)