//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {    
        public int IdAuto { get; set; }
        public double PrecioPorDia { get; set; }
        public string Descripcion { get; set; }
        public int IdProvinica { get; set; }
        public string Foto { get; set; }
        public string Categoria { get; set; }
        public int Gama { get; set; }
        public string Nombre { get; set; }
    }
}
