//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
    
        public int IdHotel { get; set; }
        public string Nombre { get; set; }
        public double PrecioPorDia { get; set; }
        public string Descripcion { get; set; }
        public int IdProvincia { get; set; }
        public string Foto { get; set; }
        public int Categoria { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Provincia Provincia { get; set; }
    }
}
